<a href="https://colab.research.google.com/github/AnastasiaKovalenko232/iad-practices/blob/main/1_2_Intro_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intro to NumPy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays (https://en.wikipedia.org/wiki/NumPy).

Numpy is incredibly fast, as it has bindings to C libraries.

In [1]:
import numpy as np

## Creation of NumPy array
### From a list

In [2]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

In [3]:
print(type(a_list))
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
a_2D = np.array(matrix)

### Using built-in methods

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2) # np.arange(start, stop, step)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.linspace(0, 10, 20) # np.linspace(start, stop, num=50)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random

### uniform
Return an array of the given shape with random samples from a uniform distribution

In [10]:
np.random.uniform(0, 1, 5) # (low, high, size)

array([0.20671105, 0.80822316, 0.01861785, 0.62280729, 0.26390081])

### randn
Return samples from the “standard normal” distribution.

In [11]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[ 1.20205902,  0.68768416],
       [ 1.66068608, -0.307551  ]])

### normal

In [12]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[1.07638742, 0.18534339],
       [0.17156155, 0.86632888],
       [0.7625881 , 0.53711441]])

### multivariate normal

In [13]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[0.2988861 , 1.25107187],
        [0.90785152, 1.35802435]],

       [[1.04686587, 1.12183682],
        [1.26520514, 3.61510337]],

       [[1.53566587, 4.04126   ],
        [1.19354118, 1.77134638]]])

### randint
Return random integers

In [14]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([54,  1,  6, 58, 47])

### seed()
The seed() method is used to initialize the random number generator.

In [15]:
np.random.seed(0)

### Operations

In [16]:
arr = np.arange(0, 10)
arr_r = arr.reshape(2, 5)
print('arr: ')
print(arr)
print('arr_r: ')
print(arr_r)

arr: 
[0 1 2 3 4 5 6 7 8 9]
arr_r: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
my_arr = np.random.randint(1, 100, 10)
print(my_arr)

[45 48 65 68 68 10 84 22 37 88]


In [18]:
my_arr.max()

np.int64(88)

In [19]:
my_arr.argmax()

np.int64(9)

In [20]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [21]:
arr_1 + arr_2

array([5, 7, 9])

In [22]:
arr_1 * arr_2

array([ 4, 10, 18])

In [23]:
np.exp(arr_1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
np.log(arr_1)

array([0.        , 0.69314718, 1.09861229])